### ISSUE TITLE
Earth orbit inaccuracy after several decades

### ISSUE THREAD

**Issue by shimmythejj** [KSP-RO/RealSolarSystem#88] opened 2016-08-15 02:52 UTC
Earth's orbital period appears to be off and it's phase relative to the rest of the inner solar system planets grows increasingly inaccurate after several decades of time warping. Other planets appear to not to be affected.

jan 1 1951 earth appears to line up with solar system modeling provided by https://www.fourmilab.ch/cgi-bin/Solar
![1951jan1_earth_correct_spot](https://cloud.githubusercontent.com/assets/5446105/17654435/f4d8316e-6257-11e6-8ab9-6457550af336.png)

Oct 15 1997 earth is out of place when comparing to https://www.fourmilab.ch/cgi-bin/Solar
![1997oct15_earth_wrong_spot2](https://cloud.githubusercontent.com/assets/5446105/17654459/1944bb8a-6258-11e6-9a76-c992f3d1d1aa.png)

Oct 15 1997 same conclusion provided with simulator at http://space.jpl.nasa.gov/
![1997oct15_earth_wrong_spot](https://cloud.githubusercontent.com/assets/5446105/17654467/2d3f1860-6258-11e6-9c9f-039ada0486d8.png)

Jan 1 2000
![2000jan1_earth_wrong_spot](https://cloud.githubusercontent.com/assets/5446105/17654487/7411aa14-6258-11e6-852c-e3189359e77b.png)

**Comment by raidernick** [comment] 2016-08-15 02:57
I can confirm this in my own game. I created a new save on a barebones RO install and over time Earth's position will drift off of official values. This is a major problem for anyone trying to replicate any real life gravity assists using earth and another body.

I compared my own screenshots by superimposing them over shimmy's and official data of the orbits at specific dates and the issue is real.

**Comment by NathanKell** [comment] 2016-08-15 04:15
That...looks bad. @eggrobin can you tell us whether that's from not taking Jupiter into account, or whether it's just an issue in orbital periods (i.e. that can be corrected sans Principia)?

**Comment by shimmythejj** [comment] 2016-08-15 20:51
Tried the semi major axis from the approximate orbital elements at http://ssd.jpl.nasa.gov/txt/p_elem_t1.txt

149597870700 meters \* 1.00000261 = 149598261150.4425 meters

after trying the new value, earth appeared to be right on track at both the start and a highly advanced calender date (1995 oct 15)
![1997oct15_earth_correct_spot](https://cloud.githubusercontent.com/assets/5446105/17678979/51b8153e-62ee-11e6-988f-848bbd5f1fb0.png)

the existing value in the RSS Kopericus config is 149494366257.0978 meters
a discrepancy roughly 100,000 km off or ~1.0007 off

I'm not sure how the existing value of the semi major axis was generated for the RSS Kopericus config, but even consulting the JPL HORIZONS Ephemeris data, there never appears to be a value for the earth moon barycenter semi major axis as low as the one original provided in the time frame of 1951 - 2000.

**Comment by raidernick** [comment] 2016-08-15 21:14
@NathanKell i discussed this with egg several hours last night and again today. He told me the issue is because he used osculating elements rather than mean orbital elements and using the earth center. The drift will be worse on bodies with significant perturbations like earth and Pluto and less noticeable on larger more massive bodies like Jupiter, which the pictures show.

Now he said as long as the new value shimmy proposed above works, which it appears to, there should be no problem in using it. There is no perfect fix for this without using principia because calculating the mean orbits is very difficult. So I say let's go for this change as I tested it myself and after 50 years the drift is not even close to what it was previously.

**Closed as completed** 2016-08-15 23:35 UTC
